### ISSUE TITLE
Question about permision to use in my game

### ISSUE THREAD

**Issue by supopur** [BaseMax/FirstRedisPython#1]
Hello, i have been making a roblox game for some time now. I decided to use redis for my save/load api as the roblox datastores are absolute mess. 

I am wondering could i use your app for my game?
If so could i fork your repo and closesource it or do i need to opensource it? Should i keep the same license? Do i need to mention you somewhere.

Thank you for your response. I am kind of new to licenses.

**Comment by BaseMax** [comment]
Dear @supopur,

I hope you are well, Merry Christmas and a happy New Year.

Thank you for your message asking about this topic. you are welcome to use the whole of the project or copy-paste a few parts of the project. don't worry about it. you allowed, it's open, so enjoy it.

> Do i need to mention you somewhere.

If you do it, It's my pleasure.

Best,
M.

**Comment by supopur** [comment]
Thank you, Merry Christmass to you too!
